name: SpleeterExample

options:
  developmentLanguage: en
  deploymentTarget:
    iOS: 15.0

packages:
  Spleeter:
    path: ../

targets:
  SpleeterExample:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: Info.plist
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.dev.SpleeterExample
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
    sources:
      - SpleeterExample
    dependencies:
      - package: Spleeter

